[project]
name = "ryseble"
version = "1.5.0"
description = "Python library for RYSE BLE Smart Shade devices (used by Home Assistant integration)."
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [ { name = "MOHAMED Kallel", email = "mohamed.kallel@yahoo.fr" } ]
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
]

dependencies = [
  "bleak>=0.22.0"
]

[project.urls]
Homepage = "https://github.com/mohamedkallel82/ryseble"
"Bug Tracker" = "https://github.com/mohamedkallel82/ryseble/issues"

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
